export type CategoryKey = "finance" | "health" | "education" | "utility" | "business";

export interface CalcMeta {
  slug: string;
  title: string;
  short: string;
  description: string;
  icon: string;
  category: CategoryKey;
  keywords: string[];
  relatedSlugs?: string[];
  hideCurrencySwitcher?: boolean;
}

export const CATEGORIES: Record<CategoryKey, { label: string; code: string; description: string }> = {
  finance: { label: "Finance", code: "FI", description: "Loans, taxes, savings and investment planning." },
  health: { label: "Health", code: "HL", description: "Body composition, nutrition and wellness tracking." },
  education: { label: "Education", code: "ED", description: "Academic performance and grade calculation." },
  utility: { label: "Utility", code: "UT", description: "Everyday converters and date calculators." },
  business: { label: "Business", code: "BS", description: "Profitability, margins, and startup metrics." },
};

export const CALCULATORS: CalcMeta[] = [
  // Phase 3 - Batch 1 Expansion
  {
    slug: "compound-interest-calculator",
    title: "Compound Interest Calculator",
    short: "Calculate how your money grows over time with compounding.",
    description: "Determine the future value of your savings or investments by projecting compound interest daily, monthly, or yearly.",
    icon: "PiggyBank", category: "finance",
    keywords: ["compound interest", "future value", "savings", "investment growth", "apy", "interest rate"],
    relatedSlugs: ["sip-investment-calculator", "loan-emi-calculator", "fd-rd-calculator"],
  },
  {
    slug: "tip-calculator",
    title: "Tip Calculator & Bill Splitter",
    short: "Quickly calculate gratuity and split the bill among friends.",
    description: "Find the exact tip amount, total bill, and split per person instantly. Perfect for dining out or service gratuities.",
    icon: "Banknote", category: "finance",
    keywords: ["tip", "gratuity", "bill split", "restaurant tip", "split bill"],
    relatedSlugs: ["discount-calculator", "gst-vat-tax-calculator", "percentage-increase-calculator"],
  },
  {
    slug: "discount-calculator",
    title: "Discount & Sale Price Calculator",
    short: "Find the final price after a discount or coupon is applied.",
    description: "Calculate what a product will actually cost after percent-off deals, cash back, or retail sales are factored in.",
    icon: "Percent", category: "utility",
    keywords: ["discount", "sale price", "coupon", "percent off", "markdown"],
    relatedSlugs: ["tip-calculator", "profit-margin-calculator", "percentage-increase-calculator"],
  },
  // Phase 3 - Batch 2 Expansion
  {
    slug: "calorie-deficit-calculator",
    title: "Calorie Deficit Calculator",
    short: "Calculate the exact calories needed to reach your target weight.",
    description: "Determine your daily calorie deficit based on your BMR, activity level, and weight loss timeline. A scientific approach to fat loss.",
    icon: "ActivitySquare", category: "health",
    keywords: ["calorie deficit", "weight loss calculator", "tdee calculator", "bmr", "fat loss", "how many calories to lose weight"],
    relatedSlugs: ["bmi-tdee-calculator", "macro-nutrient-calculator", "water-sleep-calculator"],
  },
  {
    slug: "mortgage-calculator",
    title: "Mortgage Calculator",
    short: "Plan your monthly mortgage payments with amortization.",
    description: "Calculate full mortgage terms, monthly interest, and principal payoff schedule for your new home loan.",
    icon: "Home", category: "finance",
    keywords: ["mortgage", "home loan", "amortization schedule", "house payment", "mortgage emi"],
    relatedSlugs: ["loan-emi-calculator", "rent-vs-buy-calculator", "sip-investment-calculator"],
  },
  {
    slug: "love-calculator",
    title: "Love Calculator",
    short: "Calculate the love compatibility percentage between two names.",
    description: "A fun, viral tool to test the compatibility between you and your crush. Enter two names and find out the match percentage!",
    icon: "Heart", category: "utility",
    keywords: ["love calculator", "compatibility test", "lover match", "name matching"],
    relatedSlugs: ["age-calculator", "percentage-increase-calculator"],
  },
  {
    slug: "loan-emi-calculator",
    title: "Worldwide Loan & EMI Calculator",
    short: "Plan monthly EMI, total interest and amortization for any loan worldwide.",
    description: "Multi-currency debt forecaster for home, car, or personal loans. Includes full amortization schedules and interest savings analysis.",
    icon: "Landmark", category: "finance",
    keywords: ["emi calculator", "loan math", "amortization schedule", "mortgage forecaster", "debt strategy"],
    relatedSlugs: ["rent-vs-buy-calculator", "car-loan-vs-lease-calculator", "sip-investment-calculator"],
  },
  {
    slug: "income-tax-calculator",
    title: "Global Salary & Net Pay Calculator",
    short: "Estimate take-home pay and income tax across any jurisdiction.",
    description: "Universal income forecaster to see your net salary across tax brackets with deductions and standard allowances.",
    icon: "Receipt", category: "finance",
    keywords: ["salary calculator", "net pay", "income tax calculator", "take home pay", "tax brackets"],
    relatedSlugs: ["hourly-to-salary-calculator", "retirement-fire-calculator", "gst-vat-tax-calculator"],
  },
  {
    slug: "sip-investment-calculator",
    title: "Monthly Investment (SIP) Calculator",
    short: "Project investment growth with monthly plans and compounding.",
    description: "Visualise how a recurring investment plan compounds over years with adjustable rate, tenure and step-up options.",
    icon: "TrendingUp", category: "finance",
    keywords: ["sip", "compound", "interest", "mutual fund", "investment", "recurring"],
  },
  {
    slug: "rent-vs-buy-calculator",
    title: "Rent vs Buy Calculator",
    short: "Compare the long-term cost of renting versus buying a home.",
    description: "Weigh down payment, EMI, rent inflation and home appreciation to see which option costs less over your time horizon.",
    icon: "Home", category: "finance",
    keywords: ["rent", "buy", "mortgage", "real estate", "housing"],
  },
  {
    slug: "gst-vat-tax-calculator",
    title: "GST, VAT & Sales Tax Calculator",
    short: "Calculate tax-inclusive and exclusive prices with custom rates.",
    description: "Quickly find the net price, tax amount, and total price for any product or service across standard and custom tax rates.",
    icon: "ReceiptSwissFranc", category: "finance",
    keywords: ["gst", "vat", "tax", "sales tax", "billing", "invoice"],
  },
  {
    slug: "inflation-calculator",
    title: "Inflation Calculator",
    short: "See how purchasing power changes over time with inflation.",
    description: "Calculate the real value of money across years based on average inflation rates and see the cumulative price increase.",
    icon: "TrendingDown", category: "finance",
    keywords: ["inflation", "purchasing power", "money", "cpi", "value"],
  },
  {
    slug: "fixed-deposit-calculator",
    title: "Savings Plan (FD) Calculator",
    short: "Calculate maturity amount and interest earned on savings.",
    description: "Plan your savings by calculating the interest and total maturity value for fixed deposits or time-based savings with various compounding options.",
    icon: "PiggyBank", category: "finance",
    keywords: ["fd", "savings", "interest", "fixed deposit", "investment", "time deposit"],
  },
  {
    slug: "car-loan-vs-lease-calculator",
    title: "Car Loan vs Lease Calculator",
    short: "Compare the total cost of financing versus leasing a vehicle.",
    description: "Evaluate the monthly payments, total interest, and long-term equity of buying a car with a loan versus the lower payments and lack of ownership in a lease.",
    icon: "Car", category: "finance",
    keywords: ["car loan", "lease", "vehicle finance", "auto loan"],
  },
  {
    slug: "retirement-fire-calculator",
    title: "Retirement & FIRE Calculator",
    short: "Calculate your number and timeline for financial independence.",
    description: "Project your retirement corpus and the age you can retire based on your current savings, expenses, and investment returns.",
    icon: "Flame", category: "finance",
    keywords: ["retirement", "fire", "financial independence", "savings"],
  },
  {
    slug: "bmi-tdee-calculator",
    title: "Global BMI & TDEE Calculator",
    short: "Body Mass Index, BMR and Total Daily Energy Expenditure.",
    description: "A comprehensive health forecaster providing your BMI category, Basal Metabolic Rate and TDEE based on activity level.",
    icon: "Activity", category: "health",
    keywords: ["bmi", "tdee", "bmr", "calories", "health", "metabolism"],
    relatedSlugs: ["body-fat-percentage-calculator", "ideal-weight-calculator", "pregnancy-ovulation-calculator"],
  },
  {
    slug: "body-fat-percentage-calculator",
    title: "Body Fat Percentage Calculator",
    short: "Estimate body fat percentage using Navy or BMI methods.",
    description: "Determine your body composition and fat-to-lean mass ratio using standardized photographic and anthropometric measurements.",
    icon: "Weight", category: "health",
    keywords: ["body fat", "composition", "fitness", "lean mass"],
  },
  {
    slug: "ideal-weight-calculator",
    title: "Ideal Weight Calculator",
    short: "Calculate your healthy weight range based on various formulas.",
    description: "Find your ideal body weight based on height, age, and sex using Robinson, Miller, Devine, and Hamwi formulas.",
    icon: "Weight", category: "health",
    keywords: ["ideal weight", "health", "fitness", "weight loss"],
  },
  {
    slug: "macro-nutrient-calculator",
    title: "Macro Calculator",
    short: "Calculate daily protein, carb and fat targets for your goals.",
    description: "Discover your optimal macronutrient split based on your TDEE and fitness goals (weight loss, maintenance, or muscle gain).",
    icon: "Utensils", category: "health",
    keywords: ["macros", "nutrition", "protein", "carbs", "diet"],
  },
  {
    slug: "intermittent-fasting-calculator",
    title: "Intermittent Fasting Calculator",
    short: "Plan your fasting and eating windows for weight loss.",
    description: "Calculate your 16:8, 18:6, or 20:4 fasting schedules and track your progress toward your health and weight loss targets.",
    icon: "Timer", category: "health",
    keywords: ["fasting", "intermittent fasting", "weight loss", "diet"],
  },
  {
    slug: "blood-alcohol-content-calculator",
    title: "Blood Alcohol Content (BAC) Calculator",
    short: "Estimate your blood alcohol level after consuming drinks.",
    description: "Calculate your estimated BAC based on your weight, sex, the number of drinks consumed, and the time elapsed since ingestion.",
    icon: "Beer", category: "health",
    keywords: ["bac", "alcohol", "drinking", "safety", "sobriety"],
  },
  {
    slug: "smoking-cost-calculator",
    title: "Smoking Cost Calculator",
    short: "Calculate the financial and health cost of smoking.",
    description: "See how much money you spend on cigarettes over time and estimate the life-expectancy impact of your smoking habits.",
    icon: "Cigarette", category: "health",
    keywords: ["smoking", "cost", "health", "quit smoking", "savings"],
  },
  {
    slug: "pregnancy-ovulation-calculator",
    title: "Pregnancy & Ovulation Calculator",
    short: "Estimate due date, gestational week and fertile window.",
    description: "Calculate your estimated due date from last menstrual period and project the ovulation window for cycle planning.",
    icon: "Baby", category: "health",
    keywords: ["pregnancy", "due date", "ovulation", "fertile", "lmp"],
  },
  {
    slug: "water-intake-sleep-calculator",
    title: "Water Intake & Sleep Calculator",
    short: "Daily hydration target and ideal bedtime windows.",
    description: "Recommended water intake based on weight and activity, plus optimal bed/wake times aligned with 90-minute sleep cycles.",
    icon: "Droplet", category: "health",
    keywords: ["water", "hydration", "sleep", "bedtime", "cycle"],
  },
  {
    slug: "profit-margin-calculator",
    title: "Profit Margin Calculator",
    short: "Calculate markup, margin and revenue for retail products.",
    description: "Find your gross profit margin and markup percentages to set the right selling price for your business products.",
    icon: "Briefcase", category: "business",
    keywords: ["profit", "margin", "markup", "retail", "business"],
  },
  {
    slug: "break-even-point-calculator",
    title: "Break-Even Point Calculator",
    short: "Find the unit sales needed to cover your total costs.",
    description: "Calculate the exact number of units you need to sell to reach zero profit/loss based on fixed and variable costs.",
    icon: "Target", category: "business",
    keywords: ["break even", "startup", "accounting", "profit", "sales"],
  },
  {
    slug: "crypto-investment-profit-calculator",
    title: "Crypto Profit Calculator",
    short: "Calculate potential gains or losses for your crypto trades.",
    description: "Estimate your cryptocurrency investment returns by entering buy price, sell price, and investment amount, including fees.",
    icon: "Coins", category: "business",
    keywords: ["crypto", "profit", "bitcoin", "investment", "trading"],
  },
  {
    slug: "hourly-to-salary-calculator",
    title: "Hourly to Salary Converter",
    short: "Convert hourly wage to daily, weekly and annual salary.",
    description: "Instantly convert your hourly rate into annual, monthly, and weekly salary equivalents based on your working hours.",
    icon: "Banknote", category: "business",
    keywords: ["salary", "wage", "hourly", "compensation"],
  },
  {
    slug: "age-calculator",
    title: "Exact Age & Time Interval Calculator",
    short: "Calculate your exact age in years, months, days, and seconds.",
    description: "Precision chronological tool to find your exact age and life milestones. Accounts for leap years and different month lengths with down-to-the-second accuracy.",
    icon: "Clock", category: "utility",
    keywords: ["age calculator", "date of birth calculator", "chronological age", "how old am i", "age in days", "age calculator by date of birth", "birthday calculator", "exact age"],
  },
  {
    slug: "credit-card-payoff-calculator",
    title: "Credit Card Payoff Calculator",
    short: "Plan how to clear your credit card debt efficiently.",
    description: "Plan your debt-free journey by calculating the time and interest needed to pay off your credit card balance.",
    icon: "CreditCard", category: "finance",
    keywords: ["credit card", "debt", "interest", "payoff", "credit card payoff"],
  },
  {
    slug: "date-plus-minus-calculator",
    title: "Date +/- Days Calculator",
    short: "Find a future or past date by adding/subtracting days.",
    description: "Calculate what date it will be after a certain number of days, weeks, or months, or see the gap between two specific dates.",
    icon: "CalendarPlus", category: "utility",
    keywords: ["date calculator", "add days", "subtract days", "deadline"],
  },
  {
    slug: "business-working-days-calculator",
    title: "Working Days Calculator",
    short: "Count business days between dates, excluding weekends.",
    description: "Calculate the number of business days (Mon-Fri) between any two dates, with options to exclude holiday counts.",
    icon: "Briefcase", category: "utility",
    keywords: ["business days", "working days", "deadline", "schedule"],
  },
  {
    slug: "unit-converter",
    title: "Precision Unit Converter",
    short: "Convert length, weight, speed and volume units.",
    description: "Fast bidirectional conversion across the most common metric and imperial units with 8-digit precision.",
    icon: "Ruler", category: "utility",
    keywords: ["unit converter", "metric", "imperial", "conversion", "measurement"],
  },
  {
    slug: "scientific-calculator-online",
    title: "Scientific Calculator",
    short: "Advanced math with trig, logs and power functions.",
    description: "A clean, high-precision web calculator for logarithms, trigonometry, roots and other complex mathematical operations.",
    icon: "Calculator", category: "utility",
    keywords: ["scientific calculator", "math", "trig", "log", "equations"],
  },
  {
    slug: "percentage-increase-calculator",
    title: "Percentage Calculator",
    short: "Quickly solve percentage increase, decrease and differences.",
    description: "A versatile tool to find the percentage of a number, the percentage difference between two numbers, and percentage growth or decline.",
    icon: "Percent", category: "utility",
    keywords: ["percentage", "math", "increase", "decrease", "ratio"],
  },
  {
    slug: "word-character-counter-tool",
    title: "Word & Character Counter",
    short: "Instant count for words, characters, sentences and reading time.",
    description: "A clean, private text analyzer that calculates word count, character count (with/without spaces), and estimated reading time.",
    icon: "FileType", category: "utility",
    keywords: ["word count", "character count", "writing", "editor", "seo"],
  },
  {
    slug: "gpa-to-percentage-calculator",
    title: "GPA & Percentage Calculator",
    short: "Compute weighted GPA, CGPA and percentage equivalents.",
    description: "Add courses with credit hours and grades to compute weighted GPA on the 4.0 scale, with percentage and CGPA conversions.",
    icon: "GraduationCap", category: "education",
    keywords: ["gpa", "cgpa", "percentage", "grade", "school"],
  },
  {
    slug: "one-rep-max-calculator",
    title: "1RM (One Rep Max) Calculator",
    short: "Estimate your one-rep max for any lift.",
    description: "Calculate your estimated maximum weight for one repetition based on your performance in sub-maximal sets.",
    icon: "Dumbbell", category: "health",
    keywords: ["1rm", "one rep max", "gym", "lifting", "strength"],
  },
  {
    slug: "freelance-rate-calculator",
    title: "Freelance Rate Calculator",
    short: "Determine your ideal hourly or project rate.",
    description: "Calculate what you should charge as a freelancer to cover your expenses, taxes, and desired profit.",
    icon: "BadgeDollarSign", category: "business",
    keywords: ["freelance", "hourly rate", "pricing", "business", "consulting"],
  },
  {
    slug: "qr-code-generator",
    title: "QR Code Generator",
    short: "Generate custom QR codes for URLs and text.",
    description: "Create high-quality, downloadable QR codes for your website, contact info, or any custom text instantly.",
    icon: "QrCode", category: "utility",
    keywords: ["qr code", "generator", "marketing", "link", "barcode"],
  },
  {
    slug: "running-pace-calculator",
    title: "Running Pace Calculator",
    short: "Calculate pace, time, or distance for your runs.",
    description: "Plan your training or race strategy by calculating your split times and average pace for any distance.",
    icon: "Timer", category: "health",
    keywords: ["running", "pace", "marathon", "fitness", "training"],
  },
  {
    slug: "password-generator",
    title: "Password Generator",
    short: "Create secure, random passwords instantly.",
    description: "Generate cryptographically strong passwords with custom length and character requirements for maximum security.",
    icon: "Lock", category: "utility",
    keywords: ["password", "security", "random", "generator", "safe"],
  },
  {
    slug: "tax-bracket-calculator",
    title: "Tax Bracket Calculator",
    short: "See how your income is taxed across brackets.",
    description: "Visualize how progressive tax brackets apply to your income and find your effective tax rate.",
    icon: "Percent", category: "finance",
    keywords: ["tax", "brackets", "income tax", "effective tax rate", "finance"],
  },
  {
    slug: "pregnancy-week-calculator",
    title: "Pregnancy Week Calculator",
    short: "Track your pregnancy progress week by week.",
    description: "Calculate your current week of pregnancy, trimester, and key developmental milestones for your baby.",
    icon: "Baby", category: "health",
    keywords: ["pregnancy", "weeks", "trimester", "due date", "baby"],
  },
  {
    slug: "academic-grade-calculator",
    title: "Academic Grade Calculator",
    short: "Calculate your final grade and required exam scores.",
    description: "Determine your weighted average and find out exactly what score you need on your final exam to reach your target grade.",
    icon: "GraduationCap", category: "education",
    keywords: ["grade calculator", "final grade", "weighted average", "exam score", "school grades", "academic performance"],
    relatedSlugs: ["gpa-to-percentage-calculator", "word-character-counter-tool"],
  },
  // Batch: Static Logic Tools (Pakistan)
  {
    slug: "hec-cgpa-converter",
    title: "HEC CGPA to Percentage Calculator",
    short: "Convert CGPA to percentage using HEC and university-specific scales.",
    description: "Official CGPA to percentage converter for Pakistani universities including NUST, FAST, LUMS, and UET based on HEC guidelines.",
    icon: "GraduationCap", category: "education",
    keywords: ["hec cgpa converter", "cgpa to percentage pakistan", "nust gpa calculator", "fast university gpa", "hec grading scale"],
    relatedSlugs: ["academic-grade-calculator", "gpa-to-percentage-calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "board-percentage-calculator",
    title: "Matric & Inter Percentage Calculator",
    short: "Calculate percentage and grade for all Pakistani education boards.",
    description: "Result calculator for Matric and Intermediate students across Punjab, Sindh, KPK, and Federal boards with grade and division analysis.",
    icon: "FileText", category: "education",
    keywords: ["board result calculator", "matric percentage", "inter percentage calculator", "punjab board grading", "federal board marks"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "pakistan-inflation-calculator",
    title: "Pakistan Inflation & Purchasing Power",
    short: "Calculate the real value of PKR over time using historical data.",
    description: "Compare the value of Pakistani Rupee (PKR) between any two years from 2010 to 2025 using historical CPI data.",
    icon: "TrendingUp", category: "finance",
    keywords: ["pakistan inflation calculator", "pkr purchasing power", "inflation rate pakistan history", "value of 1000 pkr"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "loan-eligibility-calculator-pakistan",
    title: "Pakistan Loan Eligibility Calculator",
    short: "Check how much home or car loan you can get based on your salary.",
    description: "Calculate your maximum loan amount and monthly EMI eligibility using standard Pakistani bank DTI (Debt-to-Income) ratios.",
    icon: "Landmark", category: "finance",
    keywords: ["loan eligibility pakistan", "home loan calculator pakistan", "car loan salary requirement", "bank loan eligibility"],
    hideCurrencySwitcher: true,
  },
  // Batch: Static Logic Tools (Worldwide)
  {
    slug: "debt-payoff-calculator",
    title: "Debt Snowball vs Avalanche Calculator",
    short: "Compare the fastest way to pay off your debts and save interest.",
    description: "Strategic debt payoff tool to compare the Snowball method (lowest balance first) vs Avalanche method (highest interest first).",
    icon: "Target", category: "finance",
    keywords: ["debt snowball vs avalanche", "debt payoff calculator", "get out of debt tool", "credit card payoff strategy"],
  },
  {
    slug: "sleep-debt-calculator",
    title: "Sleep Debt & Recovery Calculator",
    short: "Calculate your weekly sleep deficit and get a recovery plan.",
    description: "Track your sleep hours over the week to identify cumulative sleep debt and get a scientifically-backed recovery schedule.",
    icon: "Moon", category: "health",
    keywords: ["sleep debt calculator", "sleep deficit tool", "how to recover sleep", "circadian rhythm tracker"],
  },
  {
    slug: "blood-sugar-hba1c-converter",
    title: "Blood Sugar to HbA1c Converter",
    short: "Convert average blood glucose levels to HbA1c and assess risk.",
    description: "Clinical converter to estimate your HbA1c percentage from average daily blood sugar readings with a diabetes risk chart.",
    icon: "Activity", category: "health",
    keywords: ["blood sugar to hba1c", "glucose converter", "diabetes risk assessment", "average blood sugar hba1c"],
  },
  {
    slug: "net-worth-tracker",
    title: "Personal Net Worth Calculator",
    short: "Track your total assets and liabilities in one place.",
    description: "Comprehensive net worth calculator with categories for property, savings, investments, and debts for a clear financial snapshot.",
    icon: "Briefcase", category: "finance",
    keywords: ["net worth calculator", "track assets and liabilities", "personal balance sheet", "financial snapshot"],
  },
  {
    slug: "personal-carbon-footprint-calculator",
    title: "Personal Carbon Footprint Calculator",
    short: "Estimate your annual carbon emissions and environmental impact.",
    description: "Calculate your CO2 emissions from flights, driving, home energy, and diet with reduction tips and impact breakdown.",
    icon: "Leaf", category: "utility",
    keywords: ["carbon footprint calculator", "co2 emissions tool", "environmental impact calculator", "reduce carbon footprint"],
  },
  {
    slug: "solar-roi-simulator-pakistan",
    title: "Solar ROI & Net-Metering Simulator",
    short: "Simulate your solar savings and calculate payback period for your home.",
    description: "Advanced energy simulation for 2026. Calculate monthly savings, export credits, and system ROI based on current Pakistani electricity tariffs and net-metering policies.",
    icon: "Sun", category: "finance",
    keywords: ["solar roi calculator pakistan", "net metering simulator", "solar payback period", "electricity bill savings solar", "solar inverter sizing"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "freelance-fee-optimizer",
    title: "Freelance Fee & Arbitrage Optimizer",
    short: "Compare platform fees and withdrawal paths to maximize your earnings.",
    description: "Are you losing money to hidden bank fees? Use our optimizer to compare Upwork, Fiverr, and Direct Client fees against Wise, Payoneer, and Bank Wire withdrawal paths.",
    icon: "Coins", category: "finance",
    keywords: ["freelance fee calculator", "upwork vs fiverr fees", "payoneer withdrawal fee pakistan", "wise vs payoneer", "bank exchange rate calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "salary-income-tax-calculator-2026",
    title: "Pakistan Salary Tax Calculator 2026",
    short: "Calculate your monthly and yearly take-home salary after official FBR tax deductions.",
    description: "The most accurate tax calculator for the 2025-26 and 2024-25 fiscal years. Compare yearly tax slabs, calculate monthly deductions, and see your real take-home pay based on latest FBR budget rules.",
    icon: "Landmark", category: "finance",
    keywords: ["pakistan income tax calculator 2026", "fbr tax slabs 2025-26", "calculate monthly salary tax", "yearly income tax pakistan", "fbr budget 2026 tax rates"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "electricity-bill-predictor-pakistan",
    title: "Electricity Bill Predictor 2026",
    short: "Predict your electricity bill with 2026 NEPRA slabs and taxes.",
    description: "Predict your monthly electricity bill based on the latest 2026 NEPRA/DISCO slabs. Accounts for GST, FPA, and protected consumer status.",
    icon: "Zap", category: "finance",
    keywords: ["pakistan electricity bill calculator 2026", "nepra tariff slabs", "lesco bill predictor", "k-electric 2026 rates", "electricity duty calculator"],
  },
  {
    slug: "solar-system-requirement-calculator",
    title: "Solar System Size (kW) Requirement Calculator 2026",
    short: "Calculate the solar kW capacity you need based on appliances.",
    description: "Determine the ideal solar system size for your home. Input your appliance load and usage hours to calculate required PV capacity, inverter size, and 2026 configuration.",
    icon: "Sun", category: "utility",
    keywords: ["solar sizing calculator", "how many solar panels for 1.5 ton ac", "calculate solar kw requirement", "solar load calculator pakistan", "solar panel capacity for home"],
    relatedSlugs: ["solar-roi-simulator-pakistan", "electricity-bill-predictor-pakistan", "solar-battery-backup-calculator"],
  },
  {
    slug: "solar-battery-backup-calculator",
    title: "Solar Battery Backup & Runtime Calculator (kWh)",
    short: "Calculate how long your batteries will last under different loads.",
    description: "Estimate your solar battery backup time in hours. Supports 5kWh, 10kWh Lithium (LFP) modules and Tubular batteries with Depth of Discharge (DoD) analysis.",
    icon: "Battery", category: "utility",
    keywords: ["solar battery backup calculator", "5kwh lithium battery runtime", "10kwh solar battery backup hours", "lithium vs tubular battery backup", "solar storage sizing calculator"],
    relatedSlugs: ["solar-system-requirement-calculator", "solar-roi-simulator-pakistan"],
  },
  {
    slug: "solar-panel-to-kw-calculator",
    title: "Solar Panel to kW Converter",
    short: "Convert number of panels and wattage to total system kW capacity.",
    description: "Instantly calculate your total solar system capacity in kW. Enter the number of panels and their wattage (e.g., 550W, 580W) to see your total peak capacity, area required, and generation potential.",
    icon: "Grid3X3", category: "utility",
    keywords: ["solar panel to kw converter", "how many kw is 10 solar panels", "calculate solar peak capacity", "solar panel wattage converter", "solar system capacity tool"],
    relatedSlugs: ["solar-system-requirement-calculator", "solar-roi-simulator-pakistan"],
  },
  {
    slug: "social-share-preview-tool",
    title: "Social Share Preview & Meta Tag Generator",
    short: "Preview how your website looks on social media and generate meta tags.",
    description: "The ultimate debugger for your website's social media presence. Preview your Open Graph (OG) tags for Facebook, X (Twitter), LinkedIn, and WhatsApp. Generate perfectly optimized meta tags for Next.js, React, and HTML instantly.",
    icon: "Share2", category: "business",
    keywords: ["social share preview", "og tag debugger", "meta tag generator", "facebook link preview", "whatsapp link preview", "twitter card validator", "linkedin post preview"],
    relatedSlugs: ["qr-code-generator", "word-character-counter-tool"],
  },
];

export const calculatorBySlug = (slug: string) => CALCULATORS.find((c) => c.slug === slug);
