export type CategoryKey = "finance" | "health" | "education" | "utility" | "business";

export interface CalcMeta {
  slug: string;
  title: string;
  short: string;
  description: string;
  icon: string;
  category: CategoryKey;
  keywords: string[];
  relatedSlugs?: string[];
}

export const CATEGORIES: Record<CategoryKey, { label: string; code: string; description: string }> = {
  finance: { label: "Finance", code: "FI", description: "Loans, taxes, savings and investment planning." },
  health: { label: "Health", code: "HL", description: "Body composition, nutrition and wellness tracking." },
  education: { label: "Education", code: "ED", description: "Academic performance and grade calculation." },
  utility: { label: "Utility", code: "UT", description: "Everyday converters and date calculators." },
  business: { label: "Business", code: "BS", description: "Profitability, margins, and startup metrics." },
};

export const CALCULATORS: CalcMeta[] = [
  {
    slug: "loan-emi-calculator",
    title: "Worldwide Loan & EMI Calculator",
    short: "Plan monthly EMI, total interest and amortization for any loan worldwide.",
    description: "Multi-currency debt forecaster for home, car, or personal loans. Includes full amortization schedules and interest savings analysis.",
    icon: "Landmark", category: "finance",
    keywords: ["emi calculator", "loan math", "amortization schedule", "mortgage forecaster", "debt strategy"],
    relatedSlugs: ["rent-vs-buy-calculator", "car-loan-vs-lease-calculator", "sip-investment-calculator"],
  },
  {
    slug: "income-tax-calculator",
    title: "Global Salary & Net Pay Calculator",
    short: "Estimate take-home pay and income tax across any jurisdiction.",
    description: "Universal income forecaster to see your net salary across tax brackets with deductions and standard allowances.",
    icon: "Receipt", category: "finance",
    keywords: ["salary calculator", "net pay", "income tax calculator", "take home pay", "tax brackets"],
    relatedSlugs: ["hourly-to-salary-calculator", "retirement-fire-calculator", "gst-vat-tax-calculator"],
  },
  {
    slug: "sip-investment-calculator",
    title: "Monthly Investment (SIP) Calculator",
    short: "Project investment growth with monthly plans and compounding.",
    description: "Visualise how a recurring investment plan compounds over years with adjustable rate, tenure and step-up options.",
    icon: "TrendingUp", category: "finance",
    keywords: ["sip", "compound", "interest", "mutual fund", "investment", "recurring"],
  },
  {
    slug: "rent-vs-buy-calculator",
    title: "Rent vs Buy Calculator",
    short: "Compare the long-term cost of renting versus buying a home.",
    description: "Weigh down payment, EMI, rent inflation and home appreciation to see which option costs less over your time horizon.",
    icon: "Home", category: "finance",
    keywords: ["rent", "buy", "mortgage", "real estate", "housing"],
  },
  {
    slug: "gst-vat-tax-calculator",
    title: "GST, VAT & Sales Tax Calculator",
    short: "Calculate tax-inclusive and exclusive prices with custom rates.",
    description: "Quickly find the net price, tax amount, and total price for any product or service across standard and custom tax rates.",
    icon: "ReceiptSwissFranc", category: "finance",
    keywords: ["gst", "vat", "tax", "sales tax", "billing", "invoice"],
  },
  {
    slug: "inflation-calculator",
    title: "Inflation Calculator",
    short: "See how purchasing power changes over time with inflation.",
    description: "Calculate the real value of money across years based on average inflation rates and see the cumulative price increase.",
    icon: "TrendingDown", category: "finance",
    keywords: ["inflation", "purchasing power", "money", "cpi", "value"],
  },
  {
    slug: "fixed-deposit-calculator",
    title: "Savings Plan (FD) Calculator",
    short: "Calculate maturity amount and interest earned on savings.",
    description: "Plan your savings by calculating the interest and total maturity value for fixed deposits or time-based savings with various compounding options.",
    icon: "PiggyBank", category: "finance",
    keywords: ["fd", "savings", "interest", "fixed deposit", "investment", "time deposit"],
  },
  {
    slug: "car-loan-vs-lease-calculator",
    title: "Car Loan vs Lease Calculator",
    short: "Compare the total cost of financing versus leasing a vehicle.",
    description: "Evaluate the monthly payments, total interest, and long-term equity of buying a car with a loan versus the lower payments and lack of ownership in a lease.",
    icon: "Car", category: "finance",
    keywords: ["car loan", "lease", "vehicle finance", "auto loan"],
  },
  {
    slug: "retirement-fire-calculator",
    title: "Retirement & FIRE Calculator",
    short: "Calculate your number and timeline for financial independence.",
    description: "Project your retirement corpus and the age you can retire based on your current savings, expenses, and investment returns.",
    icon: "Flame", category: "finance",
    keywords: ["retirement", "fire", "financial independence", "savings"],
  },
  {
    slug: "bmi-tdee-calculator",
    title: "Global BMI & TDEE Calculator",
    short: "Body Mass Index, BMR and Total Daily Energy Expenditure.",
    description: "A comprehensive health forecaster providing your BMI category, Basal Metabolic Rate and TDEE based on activity level.",
    icon: "Activity", category: "health",
    keywords: ["bmi", "tdee", "bmr", "calories", "health", "metabolism"],
    relatedSlugs: ["body-fat-percentage-calculator", "ideal-weight-calculator", "pregnancy-ovulation-calculator"],
  },
  {
    slug: "body-fat-percentage-calculator",
    title: "Body Fat Percentage Calculator",
    short: "Estimate body fat percentage using Navy or BMI methods.",
    description: "Determine your body composition and fat-to-lean mass ratio using standardized photographic and anthropometric measurements.",
    icon: "Weight", category: "health",
    keywords: ["body fat", "composition", "fitness", "lean mass"],
  },
  {
    slug: "ideal-weight-calculator",
    title: "Ideal Weight Calculator",
    short: "Calculate your healthy weight range based on various formulas.",
    description: "Find your ideal body weight based on height, age, and sex using Robinson, Miller, Devine, and Hamwi formulas.",
    icon: "Weight", category: "health",
    keywords: ["ideal weight", "health", "fitness", "weight loss"],
  },
  {
    slug: "macro-nutrient-calculator",
    title: "Macro Calculator",
    short: "Calculate daily protein, carb and fat targets for your goals.",
    description: "Discover your optimal macronutrient split based on your TDEE and fitness goals (weight loss, maintenance, or muscle gain).",
    icon: "Utensils", category: "health",
    keywords: ["macros", "nutrition", "protein", "carbs", "diet"],
  },
  {
    slug: "intermittent-fasting-calculator",
    title: "Intermittent Fasting Calculator",
    short: "Plan your fasting and eating windows for weight loss.",
    description: "Calculate your 16:8, 18:6, or 20:4 fasting schedules and track your progress toward your health and weight loss targets.",
    icon: "Timer", category: "health",
    keywords: ["fasting", "intermittent fasting", "weight loss", "diet"],
  },
  {
    slug: "blood-alcohol-content-calculator",
    title: "Blood Alcohol Content (BAC) Calculator",
    short: "Estimate your blood alcohol level after consuming drinks.",
    description: "Calculate your estimated BAC based on your weight, sex, the number of drinks consumed, and the time elapsed since ingestion.",
    icon: "Beer", category: "health",
    keywords: ["bac", "alcohol", "drinking", "safety", "sobriety"],
  },
  {
    slug: "smoking-cost-calculator",
    title: "Smoking Cost Calculator",
    short: "Calculate the financial and health cost of smoking.",
    description: "See how much money you spend on cigarettes over time and estimate the life-expectancy impact of your smoking habits.",
    icon: "Cigarette", category: "health",
    keywords: ["smoking", "cost", "health", "quit smoking", "savings"],
  },
  {
    slug: "pregnancy-ovulation-calculator",
    title: "Pregnancy & Ovulation Calculator",
    short: "Estimate due date, gestational week and fertile window.",
    description: "Calculate your estimated due date from last menstrual period and project the ovulation window for cycle planning.",
    icon: "Baby", category: "health",
    keywords: ["pregnancy", "due date", "ovulation", "fertile", "lmp"],
  },
  {
    slug: "water-intake-sleep-calculator",
    title: "Water Intake & Sleep Calculator",
    short: "Daily hydration target and ideal bedtime windows.",
    description: "Recommended water intake based on weight and activity, plus optimal bed/wake times aligned with 90-minute sleep cycles.",
    icon: "Droplet", category: "health",
    keywords: ["water", "hydration", "sleep", "bedtime", "cycle"],
  },
  {
    slug: "profit-margin-calculator",
    title: "Profit Margin Calculator",
    short: "Calculate markup, margin and revenue for retail products.",
    description: "Find your gross profit margin and markup percentages to set the right selling price for your business products.",
    icon: "Briefcase", category: "business",
    keywords: ["profit", "margin", "markup", "retail", "business"],
  },
  {
    slug: "break-even-point-calculator",
    title: "Break-Even Point Calculator",
    short: "Find the unit sales needed to cover your total costs.",
    description: "Calculate the exact number of units you need to sell to reach zero profit/loss based on fixed and variable costs.",
    icon: "Target", category: "business",
    keywords: ["break even", "startup", "accounting", "profit", "sales"],
  },
  {
    slug: "crypto-investment-profit-calculator",
    title: "Crypto Profit Calculator",
    short: "Calculate potential gains or losses for your crypto trades.",
    description: "Estimate your cryptocurrency investment returns by entering buy price, sell price, and investment amount, including fees.",
    icon: "Coins", category: "business",
    keywords: ["crypto", "profit", "bitcoin", "investment", "trading"],
  },
  {
    slug: "hourly-to-salary-calculator",
    title: "Hourly to Salary Converter",
    short: "Convert hourly wage to daily, weekly and annual salary.",
    description: "Instantly convert your hourly rate into annual, monthly, and weekly salary equivalents based on your working hours.",
    icon: "Banknote", category: "business",
    keywords: ["salary", "wage", "hourly", "compensation"],
  },
  {
    slug: "age-calculator-date-of-birth",
    title: "Age Calculator",
    short: "Exact age in years, months, days, hours and seconds.",
    description: "Find the precise duration between two dates, your next birthday countdown and your age on any historical date.",
    icon: "Calendar", category: "utility",
    keywords: ["age", "date", "birthday", "duration"],
  },
  {
    slug: "date-plus-minus-calculator",
    title: "Date +/- Days Calculator",
    short: "Find a future or past date by adding/subtracting days.",
    description: "Calculate what date it will be after a certain number of days, weeks, or months, or see the gap between two specific dates.",
    icon: "CalendarPlus", category: "utility",
    keywords: ["date calculator", "add days", "subtract days", "deadline"],
  },
  {
    slug: "business-working-days-calculator",
    title: "Working Days Calculator",
    short: "Count business days between dates, excluding weekends.",
    description: "Calculate the number of business days (Mon-Fri) between any two dates, with options to exclude holiday counts.",
    icon: "Briefcase", category: "utility",
    keywords: ["business days", "working days", "deadline", "schedule"],
  },
  {
    slug: "unit-converter",
    title: "Precision Unit Converter",
    short: "Convert length, weight, speed and volume units.",
    description: "Fast bidirectional conversion across the most common metric and imperial units with 8-digit precision.",
    icon: "Ruler", category: "utility",
    keywords: ["unit converter", "metric", "imperial", "conversion", "measurement"],
  },
  {
    slug: "scientific-calculator-online",
    title: "Scientific Calculator",
    short: "Advanced math with trig, logs and power functions.",
    description: "A clean, high-precision web calculator for logarithms, trigonometry, roots and other complex mathematical operations.",
    icon: "Calculator", category: "utility",
    keywords: ["scientific calculator", "math", "trig", "log", "equations"],
  },
  {
    slug: "percentage-increase-calculator",
    title: "Percentage Calculator",
    short: "Quickly solve percentage increase, decrease and differences.",
    description: "A versatile tool to find the percentage of a number, the percentage difference between two numbers, and percentage growth or decline.",
    icon: "Percent", category: "utility",
    keywords: ["percentage", "math", "increase", "decrease", "ratio"],
  },
  {
    slug: "word-character-counter-tool",
    title: "Word & Character Counter",
    short: "Instant count for words, characters, sentences and reading time.",
    description: "A clean, private text analyzer that calculates word count, character count (with/without spaces), and estimated reading time.",
    icon: "FileType", category: "utility",
    keywords: ["word count", "character count", "writing", "editor", "seo"],
  },
  {
    slug: "gpa-to-percentage-calculator",
    title: "GPA & Percentage Calculator",
    short: "Compute weighted GPA, CGPA and percentage equivalents.",
    description: "Add courses with credit hours and grades to compute weighted GPA on the 4.0 scale, with percentage and CGPA conversions.",
    icon: "GraduationCap", category: "education",
    keywords: ["gpa", "cgpa", "percentage", "grade", "school"],
  },
];

export const calculatorBySlug = (slug: string) => CALCULATORS.find((c) => c.slug === slug);
