export type CategoryKey = "finance" | "health" | "education" | "utility" | "business" | "sustainability" | "benchmarks";

export interface CalcMeta {
  slug: string;
  title: string;
  short: string;
  description: string;
  icon: string;
  category: CategoryKey;
  keywords: string[];
  relatedSlugs?: string[];
  hideCurrencySwitcher?: boolean;
}

export const CATEGORIES: Record<CategoryKey, { label: string; code: string; description: string }> = {
  finance: { label: "Finance", code: "FI", description: "Loans, taxes, savings and investment planning." },
  health: { label: "Health", code: "HL", description: "Body composition, nutrition and wellness tracking." },
  education: { label: "Education", code: "ED", description: "Academic performance and grade calculation." },
  utility: { label: "Utility", code: "UT", description: "Everyday converters and date calculators." },
  business: { label: "Business", code: "BS", description: "Profitability, margins, and startup metrics." },
  sustainability: { label: "Sustainability", code: "SS", description: "Environmental impact and green energy tools." },
  benchmarks: { label: "Benchmarks", code: "BM", description: "Cognitive tests, typing speed, and human performance." },
};

export const CALCULATORS: CalcMeta[] = [
  // Phase 3 - Batch 1 Expansion
  {
    slug: "compound-interest-calculator",
    title: "Compound Interest Calculator",
    short: "Calculate how your money grows over time with compounding.",
    description: "Determine the future value of your savings or investments by projecting compound interest daily, monthly, or yearly.",
    icon: "PiggyBank", category: "finance",
    keywords: ["compound interest", "future value", "savings", "investment growth", "apy", "interest rate"],
    relatedSlugs: ["sip-investment-calculator", "loan-emi-calculator", "fd-rd-calculator"],
  },
  {
    slug: "tip-calculator",
    title: "Tip Calculator & Bill Splitter",
    short: "Quickly calculate gratuity and split the bill among friends.",
    description: "Find the exact tip amount, total bill, and split per person instantly. Perfect for dining out or service gratuities.",
    icon: "Coins", category: "finance",
    keywords: ["tip", "gratuity", "bill split", "restaurant tip", "split bill"],
    relatedSlugs: ["discount-calculator", "gst-vat-tax-calculator", "percentage-increase-calculator"],
  },
  {
    slug: "discount-calculator",
    title: "Discount & Sale Price Calculator",
    short: "Find the final price after a discount or coupon is applied.",
    description: "Calculate what a product will actually cost after percent-off deals, cash back, or retail sales are factored in.",
    icon: "Percent", category: "utility",
    keywords: ["discount", "sale price", "coupon", "percent off", "markdown"],
    relatedSlugs: ["tip-calculator", "profit-margin-calculator", "percentage-increase-calculator"],
  },
  // Phase 3 - Batch 2 Expansion
  {
    slug: "calorie-deficit-calculator",
    title: "Calorie Deficit Calculator",
    short: "Calculate the exact calories needed to reach your target weight.",
    description: "Determine your daily calorie deficit based on your BMR, activity level, and weight loss timeline. A scientific approach to fat loss.",
    icon: "Flame", category: "health",
    keywords: ["calorie deficit", "weight loss calculator", "tdee calculator", "bmr", "fat loss", "how many calories to lose weight"],
    relatedSlugs: ["bmi-tdee-calculator", "macro-nutrient-calculator", "water-sleep-calculator"],
  },
  {
    slug: "mortgage-calculator",
    title: "Mortgage Calculator",
    short: "Plan your monthly mortgage payments with amortization.",
    description: "Calculate full mortgage terms, monthly interest, and principal payoff schedule for your new home loan.",
    icon: "Home", category: "finance",
    keywords: ["mortgage", "home loan", "amortization schedule", "house payment", "mortgage emi"],
    relatedSlugs: ["loan-emi-calculator", "rent-vs-buy-calculator", "sip-investment-calculator"],
  },
  {
    slug: "love-calculator",
    title: "Love Calculator",
    short: "Calculate the love compatibility percentage between two names.",
    description: "A fun, viral tool to test the compatibility between you and your crush. Enter two names and find out the match percentage!",
    icon: "Heart", category: "utility",
    keywords: ["love calculator", "compatibility test", "lover match", "name matching"],
    relatedSlugs: ["age-calculator", "percentage-increase-calculator"],
  },
  {
    slug: "loan-emi-calculator",
    title: "Worldwide Loan & EMI Calculator",
    short: "Plan monthly EMI, total interest and amortization for any loan worldwide.",
    description: "Multi-currency debt forecaster for home, car, or personal loans. Includes full amortization schedules and interest savings analysis.",
    icon: "Banknote", category: "finance",
    keywords: ["emi calculator", "loan math", "amortization schedule", "mortgage forecaster", "debt strategy"],
    relatedSlugs: ["rent-vs-buy-calculator", "car-loan-vs-lease-calculator", "sip-investment-calculator"],
  },
  {
    slug: "income-tax-calculator",
    title: "Global Salary & Net Pay Calculator",
    short: "Estimate take-home pay and income tax across any jurisdiction.",
    description: "Universal income forecaster to see your net salary across tax brackets with deductions and standard allowances.",
    icon: "Receipt", category: "finance",
    keywords: ["salary calculator", "net pay", "income tax calculator", "take home pay", "tax brackets"],
    relatedSlugs: ["hourly-to-salary-calculator", "retirement-fire-calculator", "gst-vat-tax-calculator"],
  },
  {
    slug: "sip-investment-calculator",
    title: "Monthly Investment (SIP) Calculator",
    short: "Project investment growth with monthly plans and compounding.",
    description: "Visualise how a recurring investment plan compounds over years with adjustable rate, tenure and step-up options.",
    icon: "TrendingUp", category: "finance",
    keywords: ["sip", "compound", "interest", "mutual fund", "investment", "recurring"],
  },
  {
    slug: "rent-vs-buy-calculator",
    title: "Rent vs Buy Calculator",
    short: "Compare the long-term cost of renting versus buying a home.",
    description: "Weigh down payment, EMI, rent inflation and home appreciation to see which option costs less over your time horizon.",
    icon: "ArrowLeftRight", category: "finance",
    keywords: ["rent", "buy", "mortgage", "real estate", "housing"],
  },
  {
    slug: "gst-vat-tax-calculator",
    title: "GST, VAT & Sales Tax Calculator",
    short: "Calculate tax-inclusive and exclusive prices with custom rates.",
    description: "Quickly find the net price, tax amount, and total price for any product or service across standard and custom tax rates.",
    icon: "ReceiptSwissFranc", category: "finance",
    keywords: ["gst", "vat", "tax", "sales tax", "billing", "invoice"],
  },
  {
    slug: "inflation-calculator",
    title: "Inflation Calculator",
    short: "See how purchasing power changes over time with inflation.",
    description: "Calculate the real value of money across years based on average inflation rates and see the cumulative price increase.",
    icon: "TrendingDown", category: "finance",
    keywords: ["inflation", "purchasing power", "money", "cpi", "value"],
  },
  {
    slug: "fixed-deposit-calculator",
    title: "Savings Plan (FD) Calculator",
    short: "Calculate maturity amount and interest earned on savings.",
    description: "Plan your savings by calculating the interest and total maturity value for fixed deposits or time-based savings with various compounding options.",
    icon: "Lock", category: "finance",
    keywords: ["fd", "savings", "interest", "fixed deposit", "investment", "time deposit"],
  },
  {
    slug: "car-loan-vs-lease-calculator",
    title: "Car Loan vs Lease Calculator",
    short: "Compare the total cost of financing versus leasing a vehicle.",
    description: "Evaluate the monthly payments, total interest, and long-term equity of buying a car with a loan versus the lower payments and lack of ownership in a lease.",
    icon: "Car", category: "finance",
    keywords: ["car loan", "lease", "vehicle finance", "auto loan"],
  },
  {
    slug: "retirement-fire-calculator",
    title: "Retirement & FIRE Calculator",
    short: "Calculate your number and timeline for financial independence.",
    description: "Project your retirement corpus and the age you can retire based on your current savings, expenses, and investment returns.",
    icon: "Flame", category: "finance",
    keywords: ["retirement", "fire", "financial independence", "savings"],
  },
  {
    slug: "bmi-tdee-calculator",
    title: "Global BMI & TDEE Calculator",
    short: "Body Mass Index, BMR and Total Daily Energy Expenditure.",
    description: "A comprehensive health forecaster providing your BMI category, Basal Metabolic Rate and TDEE based on activity level.",
    icon: "ActivitySquare", category: "health",
    keywords: ["bmi", "tdee", "bmr", "calories", "health", "metabolism"],
    relatedSlugs: ["body-fat-percentage-calculator", "ideal-weight-calculator", "pregnancy-ovulation-calculator"],
  },
  {
    slug: "body-fat-percentage-calculator",
    title: "Body Fat Percentage Calculator",
    short: "Estimate body fat percentage using Navy or BMI methods.",
    description: "Determine your body composition and fat-to-lean mass ratio using standardized photographic and anthropometric measurements.",
    icon: "Weight", category: "health",
    keywords: ["body fat", "composition", "fitness", "lean mass"],
  },
  {
    slug: "ideal-weight-calculator",
    title: "Ideal Weight Calculator",
    short: "Calculate your healthy weight range based on various formulas.",
    description: "Find your ideal body weight based on height, age, and sex using Robinson, Miller, Devine, and Hamwi formulas.",
    icon: "Weight", category: "health",
    keywords: ["ideal weight", "health", "fitness", "weight loss"],
  },
  {
    slug: "macro-nutrient-calculator",
    title: "Macro Calculator",
    short: "Calculate daily protein, carb and fat targets for your goals.",
    description: "Discover your optimal macronutrient split based on your TDEE and fitness goals (weight loss, maintenance, or muscle gain).",
    icon: "Utensils", category: "health",
    keywords: ["macros", "nutrition", "protein", "carbs", "diet"],
  },
  {
    slug: "intermittent-fasting-calculator",
    title: "Intermittent Fasting Calculator",
    short: "Plan your fasting and eating windows for weight loss.",
    description: "Calculate your 16:8, 18:6, or 20:4 fasting schedules and track your progress toward your health and weight loss targets.",
    icon: "Timer", category: "health",
    keywords: ["fasting", "intermittent fasting", "weight loss", "diet"],
  },
  {
    slug: "blood-alcohol-content-calculator",
    title: "Blood Alcohol Content (BAC) Calculator",
    short: "Estimate your blood alcohol level after consuming drinks.",
    description: "Calculate your estimated BAC based on your weight, sex, the number of drinks consumed, and the time elapsed since ingestion.",
    icon: "Beer", category: "health",
    keywords: ["bac", "alcohol", "drinking", "safety", "sobriety"],
  },
  {
    slug: "smoking-cost-calculator",
    title: "Smoking Cost Calculator",
    short: "Calculate the financial and health cost of smoking.",
    description: "See how much money you spend on cigarettes over time and estimate the life-expectancy impact of your smoking habits.",
    icon: "Cigarette", category: "health",
    keywords: ["smoking", "cost", "health", "quit smoking", "savings"],
  },
  {
    slug: "pregnancy-ovulation-calculator",
    title: "Pregnancy & Ovulation Calculator",
    short: "Estimate due date, gestational week and fertile window.",
    description: "Calculate your estimated due date from last menstrual period and project the ovulation window for cycle planning.",
    icon: "Baby", category: "health",
    keywords: ["pregnancy", "due date", "ovulation", "fertile", "lmp"],
  },
  {
    slug: "water-intake-sleep-calculator",
    title: "Water Intake & Sleep Calculator",
    short: "Daily hydration target and ideal bedtime windows.",
    description: "Recommended water intake based on weight and activity, plus optimal bed/wake times aligned with 90-minute sleep cycles.",
    icon: "Droplet", category: "health",
    keywords: ["water", "hydration", "sleep", "bedtime", "cycle"],
  },
  {
    slug: "profit-margin-calculator",
    title: "Profit Margin Calculator",
    short: "Calculate markup, margin and revenue for retail products.",
    description: "Find your gross profit margin and markup percentages to set the right selling price for your business products.",
    icon: "TrendingUp", category: "business",
    keywords: ["profit", "margin", "markup", "retail", "business"],
  },
  {
    slug: "break-even-point-calculator",
    title: "Break-Even Point Calculator",
    short: "Find the unit sales needed to cover your total costs.",
    description: "Calculate the exact number of units you need to sell to reach zero profit/loss based on fixed and variable costs.",
    icon: "Target", category: "business",
    keywords: ["break even", "startup", "accounting", "profit", "sales"],
  },
  {
    slug: "crypto-investment-profit-calculator",
    title: "Crypto Profit Calculator",
    short: "Calculate potential gains or losses for your crypto trades.",
    description: "Estimate your cryptocurrency investment returns by entering buy price, sell price, and investment amount, including fees.",
    icon: "Coins", category: "business",
    keywords: ["crypto", "profit", "bitcoin", "investment", "trading"],
  },
  {
    slug: "hourly-to-salary-calculator",
    title: "Hourly to Salary Converter",
    short: "Convert hourly wage to daily, weekly and annual salary.",
    description: "Instantly convert your hourly rate into annual, monthly, and weekly salary equivalents based on your working hours.",
    icon: "Banknote", category: "business",
    keywords: ["salary", "wage", "hourly", "compensation"],
  },
  {
    slug: "age-calculator",
    title: "Exact Age & Time Interval Calculator",
    short: "Calculate your exact age in years, months, days, and seconds.",
    description: "Precision chronological tool to find your exact age and life milestones. Accounts for leap years and different month lengths with down-to-the-second accuracy.",
    icon: "Clock", category: "utility",
    keywords: ["age calculator", "date of birth calculator", "chronological age", "how old am i", "age in days", "age calculator by date of birth", "birthday calculator", "exact age"],
  },
  {
    slug: "credit-card-payoff-calculator",
    title: "Credit Card Payoff Calculator",
    short: "Plan how to clear your credit card debt efficiently.",
    description: "Plan your debt-free journey by calculating the time and interest needed to pay off your credit card balance.",
    icon: "CreditCard", category: "finance",
    keywords: ["credit card", "debt", "interest", "payoff", "credit card payoff"],
  },
  {
    slug: "date-plus-minus-calculator",
    title: "Date +/- Days Calculator",
    short: "Find a future or past date by adding/subtracting days.",
    description: "Calculate what date it will be after a certain number of days, weeks, or months, or see the gap between two specific dates.",
    icon: "CalendarPlus", category: "utility",
    keywords: ["date calculator", "add days", "subtract days", "deadline"],
  },
  {
    slug: "business-working-days-calculator",
    title: "Working Days Calculator",
    short: "Count business days between dates, excluding weekends.",
    description: "Calculate the number of business days (Mon-Fri) between any two dates, with options to exclude holiday counts.",
    icon: "CalendarCheck", category: "utility",
    keywords: ["business days", "working days", "deadline", "schedule"],
  },
  {
    slug: "unit-converter",
    title: "Precision Unit Converter",
    short: "Convert length, weight, speed and volume units.",
    description: "Fast bidirectional conversion across the most common metric and imperial units with 8-digit precision.",
    icon: "Ruler", category: "utility",
    keywords: ["unit converter", "metric", "imperial", "conversion", "measurement"],
  },
  {
    slug: "scientific-calculator-online",
    title: "Scientific Calculator",
    short: "Advanced math with trig, logs and power functions.",
    description: "A clean, high-precision web calculator for logarithms, trigonometry, roots and other complex mathematical operations.",
    icon: "Calculator", category: "utility",
    keywords: ["scientific calculator", "math", "trig", "log", "equations"],
  },
  {
    slug: "percentage-increase-calculator",
    title: "Percentage Calculator",
    short: "Quickly solve percentage increase, decrease and differences.",
    description: "A versatile tool to find the percentage of a number, the percentage difference between two numbers, and percentage growth or decline.",
    icon: "Percent", category: "utility",
    keywords: ["percentage", "math", "increase", "decrease", "ratio"],
  },
  {
    slug: "word-character-counter-tool",
    title: "Word & Character Counter",
    short: "Instant count for words, characters, sentences and reading time.",
    description: "A clean, private text analyzer that calculates word count, character count (with/without spaces), and estimated reading time.",
    icon: "FileType", category: "utility",
    keywords: ["word count", "character count", "writing", "editor", "seo"],
  },
  {
    slug: "gpa-to-percentage-calculator",
    title: "GPA & Percentage Calculator",
    short: "Compute weighted GPA, CGPA and percentage equivalents.",
    description: "Add courses with credit hours and grades to compute weighted GPA on the 4.0 scale, with percentage and CGPA conversions.",
    icon: "GraduationCap", category: "education",
    keywords: ["gpa", "cgpa", "percentage", "grade", "school"],
  },
  {
    slug: "one-rep-max-calculator",
    title: "1RM (One Rep Max) Calculator",
    short: "Estimate your one-rep max for any lift.",
    description: "Calculate your estimated maximum weight for one repetition based on your performance in sub-maximal sets.",
    icon: "Dumbbell", category: "health",
    keywords: ["1rm", "one rep max", "gym", "lifting", "strength"],
  },
  {
    slug: "freelance-rate-calculator",
    title: "Freelance Rate Calculator",
    short: "Determine your ideal hourly or project rate.",
    description: "Calculate what you should charge as a freelancer to cover your expenses, taxes, and desired profit.",
    icon: "BadgeDollarSign", category: "business",
    keywords: ["freelance", "hourly rate", "pricing", "business", "consulting"],
  },
  {
    slug: "qr-code-generator",
    title: "QR Code Generator",
    short: "Generate custom QR codes for URLs and text.",
    description: "Create high-quality, downloadable QR codes for your website, contact info, or any custom text instantly.",
    icon: "QrCode", category: "utility",
    keywords: ["qr code", "generator", "marketing", "link", "barcode"],
  },
  {
    slug: "running-pace-calculator",
    title: "Running Pace Calculator",
    short: "Calculate pace, time, or distance for your runs.",
    description: "Plan your training or race strategy by calculating your split times and average pace for any distance.",
    icon: "Timer", category: "health",
    keywords: ["running", "pace", "marathon", "fitness", "training"],
  },
  {
    slug: "password-generator",
    title: "Password Generator",
    short: "Create secure, random passwords instantly.",
    description: "Generate cryptographically strong passwords with custom length and character requirements for maximum security.",
    icon: "Lock", category: "utility",
    keywords: ["password", "security", "random", "generator", "safe"],
  },
  {
    slug: "tax-bracket-calculator",
    title: "Tax Bracket Calculator",
    short: "See how your income is taxed across brackets.",
    description: "Visualize how progressive tax brackets apply to your income and find your effective tax rate.",
    icon: "Percent", category: "finance",
    keywords: ["tax", "brackets", "income tax", "effective tax rate", "finance"],
  },
  {
    slug: "pregnancy-week-calculator",
    title: "Pregnancy Week Calculator",
    short: "Track your pregnancy progress week by week.",
    description: "Calculate your current week of pregnancy, trimester, and key developmental milestones for your baby.",
    icon: "Baby", category: "health",
    keywords: ["pregnancy", "weeks", "trimester", "due date", "baby"],
  },
  {
    slug: "academic-grade-calculator",
    title: "Academic Grade Calculator",
    short: "Calculate your final grade and required exam scores.",
    description: "Determine your weighted average and find out exactly what score you need on your final exam to reach your target grade.",
    icon: "GraduationCap", category: "education",
    keywords: ["grade calculator", "final grade", "weighted average", "exam score", "school grades", "academic performance"],
    relatedSlugs: ["gpa-to-percentage-calculator", "word-character-counter-tool"],
  },
  // Batch: Static Logic Tools (Pakistan)
  {
    slug: "hec-cgpa-converter",
    title: "HEC CGPA to Percentage Calculator",
    short: "Convert CGPA to percentage using HEC and university-specific scales.",
    description: "Official CGPA to percentage converter for Pakistani universities including NUST, FAST, LUMS, and UET based on HEC guidelines.",
    icon: "GraduationCap", category: "education",
    keywords: ["hec cgpa converter", "cgpa to percentage pakistan", "nust gpa calculator", "fast university gpa", "hec grading scale"],
    relatedSlugs: ["academic-grade-calculator", "gpa-to-percentage-calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "board-percentage-calculator",
    title: "Matric & Inter Percentage Calculator",
    short: "Calculate percentage and grade for all Pakistani education boards.",
    description: "Result calculator for Matric and Intermediate students across Punjab, Sindh, KPK, and Federal boards with grade and division analysis.",
    icon: "FileText", category: "education",
    keywords: ["board result calculator", "matric percentage", "inter percentage calculator", "punjab board grading", "federal board marks"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "pakistan-inflation-calculator",
    title: "Pakistan Inflation & Purchasing Power",
    short: "Calculate the real value of PKR over time using historical data.",
    description: "Compare the value of Pakistani Rupee (PKR) between any two years from 2010 to 2025 using historical CPI data.",
    icon: "TrendingUp", category: "finance",
    keywords: ["pakistan inflation calculator", "pkr purchasing power", "inflation rate pakistan history", "value of 1000 pkr"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "loan-eligibility-calculator-pakistan",
    title: "Pakistan Loan Eligibility Calculator",
    short: "Check how much home or car loan you can get based on your salary.",
    description: "Calculate your maximum loan amount and monthly EMI eligibility using standard Pakistani bank DTI (Debt-to-Income) ratios.",
    icon: "BadgeCheck", category: "finance",
    keywords: ["loan eligibility pakistan", "home loan calculator pakistan", "car loan salary requirement", "bank loan eligibility"],
    hideCurrencySwitcher: true,
  },
  // Batch: Static Logic Tools (Worldwide)
  {
    slug: "debt-payoff-calculator",
    title: "Debt Snowball vs Avalanche Calculator",
    short: "Compare the fastest way to pay off your debts and save interest.",
    description: "Strategic debt payoff tool to compare the Snowball method (lowest balance first) vs Avalanche method (highest interest first).",
    icon: "Target", category: "finance",
    keywords: ["debt snowball vs avalanche", "debt payoff calculator", "get out of debt tool", "credit card payoff strategy"],
  },
  {
    slug: "sleep-debt-calculator",
    title: "Sleep Debt & Recovery Calculator",
    short: "Calculate your weekly sleep deficit and get a recovery plan.",
    description: "Track your sleep hours over the week to identify cumulative sleep debt and get a scientifically-backed recovery schedule.",
    icon: "Moon", category: "health",
    keywords: ["sleep debt calculator", "sleep deficit tool", "how to recover sleep", "circadian rhythm tracker"],
  },
  {
    slug: "blood-sugar-hba1c-converter",
    title: "Blood Sugar to HbA1c Converter",
    short: "Convert average blood glucose levels to HbA1c and assess risk.",
    description: "Clinical converter to estimate your HbA1c percentage from average daily blood sugar readings with a diabetes risk chart.",
    icon: "Droplets", category: "health",
    keywords: ["blood sugar to hba1c", "glucose converter", "diabetes risk assessment", "average blood sugar hba1c"],
  },
  {
    slug: "net-worth-tracker",
    title: "Personal Net Worth Calculator",
    short: "Track your total assets and liabilities in one place.",
    description: "Comprehensive net worth calculator with categories for property, savings, investments, and debts for a clear financial snapshot.",
    icon: "Briefcase", category: "finance",
    keywords: ["net worth calculator", "track assets and liabilities", "personal balance sheet", "financial snapshot"],
  },
  {
    slug: "personal-carbon-footprint-calculator",
    title: "Personal Carbon Footprint Calculator",
    short: "Estimate your annual carbon emissions and environmental impact.",
    description: "Calculate your CO2 emissions from flights, driving, home energy, and diet with reduction tips and impact breakdown.",
    icon: "Leaf", category: "utility",
    keywords: ["carbon footprint calculator", "co2 emissions tool", "environmental impact calculator", "reduce carbon footprint"],
  },
  {
    slug: "solar-roi-simulator-pakistan",
    title: "Solar ROI & Net-Metering Simulator",
    short: "Simulate your solar savings and calculate payback period for your home.",
    description: "Advanced energy simulation for 2026. Calculate monthly savings, export credits, and system ROI based on current Pakistani electricity tariffs and net-metering policies.",
    icon: "Sun", category: "finance",
    keywords: ["solar roi calculator pakistan", "net metering simulator", "solar payback period", "electricity bill savings solar", "solar inverter sizing"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "freelance-fee-optimizer",
    title: "Freelance Fee & Arbitrage Optimizer",
    short: "Compare platform fees and withdrawal paths to maximize your earnings.",
    description: "Are you losing money to hidden bank fees? Use our optimizer to compare Upwork, Fiverr, and Direct Client fees against Wise, Payoneer, and Bank Wire withdrawal paths.",
    icon: "Coins", category: "finance",
    keywords: ["freelance fee calculator", "upwork vs fiverr fees", "payoneer withdrawal fee pakistan", "wise vs payoneer", "bank exchange rate calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "salary-income-tax-calculator-2026",
    title: "Pakistan Salary Tax Calculator 2026",
    short: "Calculate your monthly and yearly take-home salary after official FBR tax deductions.",
    description: "The most accurate tax calculator for the 2025-26 and 2024-25 fiscal years. Compare yearly tax slabs, calculate monthly deductions, and see your real take-home pay based on latest FBR budget rules.",
    icon: "Wallet", category: "finance",
    keywords: ["pakistan income tax calculator 2026", "fbr tax slabs 2025-26", "calculate monthly salary tax", "yearly income tax pakistan", "fbr budget 2026 tax rates"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "electricity-bill-predictor-pakistan",
    title: "Electricity Bill Predictor 2026",
    short: "Predict your electricity bill with 2026 NEPRA slabs and taxes.",
    description: "Predict your monthly electricity bill based on the latest 2026 NEPRA/DISCO slabs. Accounts for GST, FPA, and protected consumer status.",
    icon: "Zap", category: "finance",
    keywords: ["pakistan electricity bill calculator 2026", "nepra tariff slabs", "lesco bill predictor", "k-electric 2026 rates", "electricity duty calculator"],
  },
  {
    slug: "solar-system-requirement-calculator",
    title: "Solar System Size (kW) Requirement Calculator 2026",
    short: "Calculate the solar kW capacity you need based on appliances.",
    description: "Determine the ideal solar system size for your home. Input your appliance load and usage hours to calculate required PV capacity, inverter size, and 2026 configuration.",
    icon: "Sun", category: "utility",
    keywords: ["solar sizing calculator", "how many solar panels for 1.5 ton ac", "calculate solar kw requirement", "solar load calculator pakistan", "solar panel capacity for home"],
    relatedSlugs: ["solar-roi-simulator-pakistan", "electricity-bill-predictor-pakistan", "solar-battery-backup-calculator"],
  },
  {
    slug: "solar-battery-backup-calculator",
    title: "Solar Battery Backup & Runtime Calculator (kWh)",
    short: "Calculate how long your batteries will last under different loads.",
    description: "Estimate your solar battery backup time in hours. Supports 5kWh, 10kWh Lithium (LFP) modules and Tubular batteries with Depth of Discharge (DoD) analysis.",
    icon: "Battery", category: "utility",
    keywords: ["solar battery backup calculator", "5kwh lithium battery runtime", "10kwh solar battery backup hours", "lithium vs tubular battery backup", "solar storage sizing calculator"],
    relatedSlugs: ["solar-system-requirement-calculator", "solar-roi-simulator-pakistan"],
  },
  {
    slug: "solar-panel-to-kw-calculator",
    title: "Solar Panel to kW Converter",
    short: "Convert number of panels and wattage to total system kW capacity.",
    description: "Instantly calculate your total solar system capacity in kW. Enter the number of panels and their wattage (e.g., 550W, 580W) to see your total peak capacity, area required, and generation potential.",
    icon: "Grid3X3", category: "utility",
    keywords: ["solar panel to kw converter", "how many kw is 10 solar panels", "calculate solar peak capacity", "solar panel wattage converter", "solar system capacity tool"],
    relatedSlugs: ["solar-system-requirement-calculator", "solar-roi-simulator-pakistan"],
  },
  {
    slug: "social-share-preview-tool",
    title: "Social Share Preview & Meta Tag Generator",
    short: "Preview how your website looks on social media and generate meta tags.",
    description: "The ultimate debugger for your website's social media presence. Preview your Open Graph (OG) tags for Facebook, X (Twitter), LinkedIn, and WhatsApp. Generate perfectly optimized meta tags for Next.js, React, and HTML instantly.",
    icon: "Share", category: "utility",
    keywords: ["social share preview", "og tag debugger", "meta tag generator", "facebook link preview", "whatsapp link preview", "twitter card validator", "linkedin post preview"],
    relatedSlugs: ["qr-code-generator", "word-character-counter-tool"],
  },
  {
    slug: "university-merit-aggregate-calculator",
    title: "University Merit (Aggregate) Calculator",
    short: "Calculate your aggregate merit for NUST, UET, FAST, and GIKI.",
    description: "Calculate your university admission merit score based on Matric, Inter, and Entry Test scores. Supports custom weights for all major universities like NUST (NET), UET (ECAT), FAST, and GIKI.",
    icon: "GraduationCap", category: "education",
    keywords: ["merit calculator", "aggregate calculator", "university admission merit", "nust merit calculator", "uet aggregate calculator", "fast university merit", "how to calculate merit", "aggregate calculator pakistan", "admission aggregate"],
    relatedSlugs: ["hec-cgpa-converter", "board-percentage-calculator", "academic-grade-calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "pakistan-mobile-pta-tax-calculator",
    title: "Pakistan Mobile (PTA) Tax Calculator 2026",
    short: "Calculate the official PTA tax for mobile phones using 2026 FBR rates.",
    description: "Get the most accurate estimate of PTA/DIRBS taxes for iPhone, Samsung, and other smartphones. Updated with the April 2026 FBR Valuation Ruling No. 2070 for Passport and CNIC registration.",
    icon: "Smartphone", category: "finance",
    keywords: ["pta tax calculator 2026", "mobile tax pakistan", "iphone 17 pta tax", "fbr valuation ruling 2070", "pta tax on passport vs cnic", "dirbs tax calculator"],
    relatedSlugs: ["salary-income-tax-calculator-2026", "electricity-bill-predictor-pakistan"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "ai-api-token-cost-calculator",
    title: "AI API Token Cost Estimator",
    short: "Estimate API costs for GPT-4o, Claude, and Gemini per million tokens.",
    description: "Calculate your LLM expenses with precision. Compare pricing for OpenAI, Anthropic, and Google APIs. Includes support for Batch API discounts and Prompt Caching for 2026.",
    icon: "Zap", category: "business",
    keywords: ["ai api pricing 2026", "gpt-4o cost calculator", "claude 3.5 sonnet price", "token cost estimator", "llm cost comparison", "openai batch api discount"],
    relatedSlugs: ["profit-margin-calculator", "hourly-to-salary-calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "pakistan-car-registration-fee-calculator",
    title: "Pakistan Car Registration Fee Calculator 2026",
    short: "Calculate registration fees and withholding tax for Punjab, Sindh, and Islamabad.",
    description: "Get the latest estimates for new car registration in Pakistan. Includes provincial fees, Filer vs Non-Filer withholding tax (WHT) slabs, and luxury taxes for 2026.",
    icon: "Car", category: "finance",
    keywords: ["car registration fee pakistan 2026", "punjab car registration calculator", "sindh excise registration rates", "islamabad car registration tax", "filer vs non-filer car tax", "advance income tax on cars"],
    relatedSlugs: ["salary-income-tax-calculator-2026", "loan-eligibility-calculator-pakistan"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "zakat-calculator-pakistan-2026",
    title: "Zakat Calculator Pakistan 2026",
    short: "Calculate your Zakat accurately with latest Nisab, gold, and silver rates for 2026.",
    description: "Use our comprehensive Zakat calculator to determine your obligations. Covers gold, silver, cash, investments, and business assets based on 2026 Nisab values.",
    icon: "Coins", category: "finance",
    keywords: ["zakat calculator pakistan 2026", "nisab for zakat 2026 pakistan", "gold price for zakat", "zakat on property and investments", "islamic wealth tax calculator"],
    relatedSlugs: ["salary-income-tax-calculator-2026", "loan-emi-calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "solar-net-billing-calculator-pakistan",
    title: "Solar Net Billing (Buyback) Calculator 2026",
    short: "Calculate your savings under the 2026 Net Billing system.",
    description: "Don't get confused by the new solar rules. Calculate your actual bill reduction using differentiated rates for exported and self-consumed solar units in Pakistan.",
    icon: "Sun", category: "finance",
    keywords: ["solar net billing calculator", "solar buyback rate pakistan", "solar savings calculator 2026", "net billing vs net metering", "lesco solar rates", "k-electric solar credit"],
    relatedSlugs: ["solar-roi-simulator-pakistan", "electricity-bill-predictor-pakistan"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "freelance-tax-residency-optimizer",
    title: "Freelance Tax & Residency Optimizer 2026",
    short: "Optimize your remote income tax and withdrawal arbitrage.",
    description: "Compare Filer vs Non-Filer tax, SECP registration, and US LLC benefits. Find the best withdrawal path (Wise vs Payoneer) to maximize your PKR earnings in 2026.",
    icon: "Coins", category: "business",
    keywords: ["freelance tax pakistan 2026", "filer vs non filer tax", "remote work tax optimization", "wise vs payoneer fees 2026", "secp vs sole proprietor tax"],
    relatedSlugs: ["freelance-rate-calculator", "freelance-fee-optimizer"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "ai-agent-efficiency-roi-calculator",
    title: "AI Agent Efficiency & ROI Calculator",
    short: "Measure the dollar value of AI productivity gains.",
    description: "Calculate how much your AI agents (Claude 4.7, GPT-5.4) are actually saving your business by comparing labor costs saved vs API token expenses.",
    icon: "Zap", category: "business",
    keywords: ["ai roi calculator", "ai agent productivity estimator", "llm cost savings", "claude 4.7 vs gpt-5.4 roi", "ai efficiency calculator for business"],
    relatedSlugs: ["ai-api-token-cost-calculator", "profit-margin-calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "urban-cooling-tree-multiplier",
    title: "Urban Cooling & Tree Multiplier 2026",
    short: "Calculate how trees can lower your home's temperature.",
    description: "Determine the exact number of indigenous trees needed to reduce heat-island effects around your property and save on AC cooling costs.",
    icon: "Trees", category: "sustainability",
    keywords: ["urban cooling tree calculator", "best trees for cooling lahore", "amaltas vs neem cooling impact", "natural house cooling pakistan", "tree plantation impact calculator"],
    relatedSlugs: ["solar-net-billing-calculator-pakistan", "electricity-bill-predictor-pakistan"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "ai-water-footprint-calculator",
    title: "AI Water Footprint Calculator",
    short: "Measure the water cost of your digital AI habits.",
    description: "Every AI prompt has a water cost for data center cooling. Calculate your personal AI water footprint and learn how to use tech sustainably.",
    icon: "Droplets", category: "sustainability",
    keywords: ["ai water consumption calculator", "water footprint of gpt-5", "claude 4.7 water cost per prompt", "sustainable ai usage", "digital water footprint tool"],
    relatedSlugs: ["ai-agent-efficiency-roi-calculator", "ai-api-token-cost-calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "plastic-to-oxygen-impact-map",
    title: "Plastic-to-Oxygen Impact Map",
    short: "Convert plastic savings into oxygen & ocean protection.",
    description: "See the real-world impact of your zero-waste journey. Translates saved plastic bottles and bags into oxygen produced by equivalent trees.",
    icon: "Globe", category: "sustainability",
    keywords: ["plastic saving impact calculator", "zero waste oxygen equivalency", "ocean protection calculator", "plastic vs trees impact", "sustainability progress tracker"],
    relatedSlugs: ["urban-cooling-tree-multiplier", "dietary-land-use-restoration"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "ev-grid-cleanliness-auditor",
    title: "EV Grid Cleanliness Auditor 2026",
    short: "Is your EV actually clean? Check your local grid source.",
    description: "Calculate the 'True Green' score of your electric vehicle by factoring in your local energy grid's dependence on coal vs renewables in 2026.",
    icon: "Zap", category: "sustainability",
    keywords: ["ev carbon footprint pakistan", "grid cleanliness auditor", "electric car vs petrol 2026", "ev emissions calculator", "sustainable ev charging times"],
    relatedSlugs: ["solar-net-billing-calculator-pakistan", "fuel-cost-calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "dietary-land-use-restoration",
    title: "Dietary Land Use & Restoration Tool",
    short: "Calculate the forest area saved by your diet choices.",
    description: "Measure how much land and forest can be restored by small shifts in your weekly diet. Translates meat reduction into square meters of biodiversity.",
    icon: "Leaf", category: "sustainability",
    keywords: ["dietary land use calculator", "forest restoration diet tool", "meat vs plant land footprint", "sustainable eating impact", "biodiversity support calculator"],
    relatedSlugs: ["urban-cooling-tree-multiplier", "plastic-to-oxygen-impact-map"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "microplastic-ocean-protection",
    title: "Microplastic & Ocean Protection Tool",
    short: "Measure microplastics saved by better laundry habits.",
    description: "Predict how many microplastic particles you prevent from entering the ocean by optimizing your laundry temperature and frequency.",
    icon: "Waves", category: "sustainability",
    keywords: ["microplastic calculator", "laundry water protection", "prevent ocean pollution tool", "sustainable washing machine habits", "microplastic fiber savings"],
    relatedSlugs: ["dietary-land-use-restoration", "ai-water-footprint-calculator"],
    hideCurrencySwitcher: true,
  },
  {
    slug: "gps-speedometer-online",
    title: "GPS Speedometer Online",
    short: "A clean, high-precision GPS speedometer for any type of travel.",
    description: "Measure your real-time speed with our high-precision GPS speedometer. Perfect for cars, trains, buses, or walking. Features include max speed tracking, trip distance, and HUD mode.",
    icon: "Navigation", category: "utility",
    keywords: ["gps speedometer online", "live speed tracker", "accurate speedometer", "mobile gps speedo", "web speedometer"],
    relatedSlugs: ["car-performance-speed-test", "unit-converter"],
  },
  {
    slug: "car-performance-speed-test",
    title: "Car GPS Speedometer & Performance Tracker",
    short: "Real-time car speed, 0-60 timer, and trip analytics for your vehicle.",
    description: "Turn your phone into a high-precision GPS speedometer. Track live speed, measure 0-60 performance, log trip distance, and use HUD (Head-Up Display) mode for windshield projection.",
    icon: "Car", category: "utility",
    keywords: ["gps speedometer", "live car speed", "0-60 timer", "hud speedometer", "trip tracker", "performance box"],
    relatedSlugs: ["car-loan-vs-lease-calculator", "unit-converter"],
  },
  {
    slug: "train-speed-test-live",
    title: "Live Train Speed Test (GPS)",
    short: "Track the real-time speed of your train trip using GPS.",
    description: "Curious how fast your train is going? Use our live GPS train speedometer to track real-time rail speed, max velocity, and total trip distance directly from your seat.",
    icon: "Train", category: "utility",
    keywords: ["train speed test", "live rail speed", "how fast is my train", "railway speedometer", "gps train tracker"],
    relatedSlugs: ["car-performance-speed-test", "flight-speed-tracker-gps"],
  },
  {
    slug: "flight-speed-tracker-gps",
    title: "Live Flight Speed & Altitude Tracker",
    short: "Track airplane speed and altitude in real-time via GPS.",
    description: "Monitor your flight's speed and altitude in real-time. Our GPS-based flight tracker works from your window seat, providing live ground speed and height data without needing Wi-Fi.",
    icon: "Plane", category: "utility",
    keywords: ["flight speed tracker", "airplane speed live", "gps altitude tracker", "flight telemetry", "how fast is my plane"],
    relatedSlugs: ["train-speed-test-live", "car-performance-speed-test"],
  },
  {
    slug: "roller-coaster-speed-tracker",
    title: "Roller Coaster Speed & G-Force Tracker",
    short: "Measure max speed and G-force on any roller coaster ride.",
    description: "Track the thrill of your next roller coaster! Measure peak speeds, record G-force data using your phone's sensors, and log the maximum drop velocity in real-time.",
    icon: "Zap", category: "utility",
    keywords: ["roller coaster speed", "coaster speedometer", "track g-force online", "theme park speed test", "drop speed tracker"],
    relatedSlugs: ["high-speed-elevator-test", "car-performance-speed-test"],
  },
  {
    slug: "high-speed-elevator-test",
    title: "Elevator Speed Test (Feet per Minute)",
    short: "Measure the vertical speed of any skyscraper elevator.",
    description: "Test the vertical velocity of high-speed elevators in skyscrapers. Get real-time data in feet per minute (fpm) or meters per second, perfect for checking world-class lift performance.",
    icon: "ArrowUpCircle", category: "utility",
    keywords: ["elevator speed test", "skyscraper lift speed", "fpm calculator", "elevator velocity tracker", "how fast is this lift"],
    relatedSlugs: ["roller-coaster-speed-tracker", "flight-speed-tracker-gps"],
  },
  {
    slug: "cycling-speedometer-online",
    title: "Online Cycling Speedometer (GPS)",
    short: "Professional-grade bike speedometer for your cycling trips.",
    description: "Turn your smartphone into a professional cycling computer. Track live bike speed, average pace, max velocity, and total distance with our high-precision GPS bike speedometer.",
    icon: "Bike", category: "utility",
    keywords: ["cycling speedometer", "online bike tracker", "live bicycle speed", "cycling pace calculator", "gps bike computer"],
    relatedSlugs: ["running-speedometer-test", "car-performance-speed-test"],
  },
  {
    slug: "boat-speed-tracker-knots",
    title: "GPS Boat Speed Tracker (Knots)",
    short: "Measure marine speed in knots and nautical miles via GPS.",
    description: "Navigate with precision using our marine GPS speedometer. Track boat speed in knots, calculate nautical miles, and monitor your heading and coordinates live on the water.",
    icon: "Anchor", category: "utility",
    keywords: ["boat speed tracker", "knots speedometer", "marine gps tracker", "how fast is my boat", "nautical miles calculator"],
    relatedSlugs: ["car-performance-speed-test", "cycling-speedometer-online"],
  },
  {
    slug: "e-scooter-speedometer",
    title: "Electric Scooter Speedometer",
    short: "Track your e-scooter's real-time speed and trip stats.",
    description: "Monitor your electric scooter rides with our dedicated GPS speedometer. Perfect for Segway, Xiaomi, and custom e-scooters to track live speed and battery-saving trip data.",
    icon: "Zap", category: "utility",
    keywords: ["e-scooter speedometer", "electric scooter speed", "scooter tracker gps", "segway speed test", "xiaomi scooter speed"],
    relatedSlugs: ["cycling-speedometer-online", "car-performance-speed-test"],
  },
  {
    slug: "ski-snowboard-speed-tracker",
    title: "Ski & Snowboard Speed Tracker",
    short: "Track your maximum downhill speed on the slopes.",
    description: "Measure your peak velocity on the ski slopes. Our GPS tracker records your maximum downhill speed, average pace, and total run distance for skiing and snowboarding.",
    icon: "Snowflake", category: "utility",
    keywords: ["ski speed tracker", "snowboard speedometer", "downhill speed test", "winter sports gps", "how fast am i skiing"],
    relatedSlugs: ["roller-coaster-speed-tracker", "running-speedometer-test"],
  },
  {
    slug: "running-speedometer-test",
    title: "Running Speedometer & Pace Test",
    short: "Track your running speed and sprinting pace live.",
    description: "Optimize your training with our live running speedometer. Track your current sprinting speed, average running pace, and total distance using high-precision mobile GPS.",
    icon: "Footprints", category: "utility",
    keywords: ["running speed test", "sprint speedometer", "live running pace", "how fast am i running", "jogging speed tracker"],
    relatedSlugs: ["cycling-speedometer-online", "car-performance-speed-test"],
  },
  {
    slug: "horse-riding-speed-tracker",
    title: "Horse Riding Speed Tracker (GPS)",
    short: "Monitor your horse's trot, canter, and gallop speeds.",
    description: "Track your equestrian performance with our GPS horse speedometer. Measure speeds during trot, canter, and gallop, and log your total trail distance in real-time.",
    icon: "Dna", category: "utility",
    keywords: ["horse riding speed", "equestrian tracker", "gallop speed test", "canter speedometer", "gps horse tracker"],
    relatedSlugs: ["running-speedometer-test", "boat-speed-tracker-knots"],
  },
  {
    slug: "human-reaction-time-test",
    title: "Human Reaction Time Test",
    short: "Measure your brain's processing speed with this interactive reaction test.",
    description: "Measure your reaction speed with this simple test. Click the screen as fast as you can when it turns from red to green to see your score.",
    icon: "Zap", category: "benchmarks",
    keywords: ["reaction time test", "human benchmark", "click speed test", "reflex test", "brain speed"],
    relatedSlugs: ["sleep-debt-calculator", "water-intake-sleep-calculator"],
  },
  {
    slug: "sequence-memory-test",
    title: "Sequence Memory (Pattern) Test",
    short: "Repeat the pattern as it gets longer. How far can you go?",
    description: "Test your memory by repeating a sequence of tiles that light up. Every time you get it right, the pattern adds one more step to make it harder.",
    icon: "Brain", category: "benchmarks",
    keywords: ["sequence memory test", "memory matrix", "brain training online", "short term memory test", "simon says game"],
    relatedSlugs: ["human-reaction-time-test", "visual-memory-test"],
  },
  {
    slug: "aim-trainer",
    title: "Aim Trainer Test",
    short: "How quickly can you hit all the targets?",
    description: "Test your aim and speed with this interactive aim trainer. Click all 30 targets as fast as you can to see your average click time and accuracy score.",
    icon: "Target", category: "benchmarks",
    keywords: ["aim trainer", "fps aim test", "mouse accuracy test", "reaction speed test", "gaming reflexes"],
    relatedSlugs: ["human-reaction-time-test", "typing-speed-test"],
  },
  {
    slug: "number-memory-test",
    title: "Number Memory Test",
    short: "Remember the longest number you can.",
    description: "Test your memory by remembering a sequence of numbers that gets longer every time you get it right. See if you can beat the average score of 7 digits.",
    icon: "Hash", category: "benchmarks",
    keywords: ["number memory test", "digit span test", "iq memory test", "brain training numbers", "short term memory"],
    relatedSlugs: ["verbal-memory-test", "sequence-memory-test"],
  },
  {
    slug: "verbal-memory-test",
    title: "Verbal Memory Test",
    short: "Keep as many words in short term memory as possible.",
    description: "Test your verbal memory by keeping track of words. You will be shown words one by one—you just have to say if you have seen the word before or if it is new.",
    icon: "BookOpen", category: "benchmarks",
    keywords: ["verbal memory test", "word recognition test", "language memory", "brain games online", "memory benchmark"],
    relatedSlugs: ["number-memory-test", "chimp-test"],
  },
  {
    slug: "chimp-test",
    title: "Chimpanzee Memory Test",
    short: "Are you smarter than a chimpanzee?",
    description: "Test your memory against a famous chimpanzee experiment. Numbers appear on a grid and hide behind squares—click them in the right order to win.",
    icon: "Grid3X3", category: "benchmarks",
    keywords: ["chimp test", "chimpanzee memory", "working memory test", "grid pattern memory", "iq test online"],
    relatedSlugs: ["visual-memory-test", "sequence-memory-test"],
  },
  {
    slug: "visual-memory-test",
    title: "Visual Memory Test",
    short: "Remember an increasingly large board of squares.",
    description: "Test your visual memory by remembering where the squares light up on the board. The grid gets bigger and more difficult as you move to higher levels.",
    icon: "LayoutGrid", category: "benchmarks",
    keywords: ["visual memory test", "spatial memory", "grid memory game", "brain training", "pattern recognition"],
    relatedSlugs: ["chimp-test", "sequence-memory-test"],
  },
  {
    slug: "typing-speed-test",
    title: "Typing Speed Test (WPM)",
    short: "How many words per minute can you type?",
    description: "Test your typing speed and accuracy with this easy WPM test. Type the text as fast as you can to see your typing speed and character accuracy score.",
    icon: "Keyboard", category: "benchmarks",
    keywords: ["typing speed test", "wpm test online", "typing accuracy", "keyboard speed test", "fast typing"],
    relatedSlugs: ["aim-trainer", "human-reaction-time-test"],
  },
];

export const calculatorBySlug = (slug: string) => CALCULATORS.find((c) => c.slug === slug);
